import type { AppSettings, ShortcutBindings } from "./types";

export const highlightColors = ["#f7d86a", "#83d9b7", "#f2a0a1", "#9db7ff", "#d7b7ff"];

export const themeSeriesOptions = [
  {
    id: "classic",
    label: "经典纸书",
    description: "当前所有主题，保留温和的纸面阅读感。",
    defaultTheme: "paper",
    previewBg: "#fffdf7",
    previewInk: "#20211d",
    accent: "#c3452b",
  },
  {
    id: "archive",
    label: "档案馆",
    description: "像在整理馆藏、卡片和旧档案。",
    defaultTheme: "archive",
    previewBg: "#f5ecd8",
    previewInk: "#241f19",
    accent: "#8a3d2d",
  },
  {
    id: "atelier",
    label: "工作台",
    description: "更锋利的网格、面板和工具感。",
    defaultTheme: "blueprint",
    previewBg: "#eef4f7",
    previewInk: "#15232d",
    accent: "#286f9d",
  },
  {
    id: "terminal",
    label: "低光终端",
    description: "低照度、高对比，适合沉浸批注。",
    defaultTheme: "console",
    previewBg: "#101513",
    previewInk: "#d8f2df",
    accent: "#60d394",
  },
  {
    id: "poster",
    label: "拼贴海报",
    description: "斜切色块、纸张拼贴和强烈视觉节奏。",
    defaultTheme: "riso",
    previewBg: "#fff056",
    previewInk: "#151515",
    accent: "#ff4d38",
  },
  {
    id: "glass",
    label: "光谱玻璃",
    description: "柔光色层、半透明面板和轻盈漂浮感。",
    defaultTheme: "prism",
    previewBg: "#eef8f5",
    previewInk: "#142023",
    accent: "#ff7a70",
  },
  {
    id: "flight",
    label: "夜航仪表",
    description: "航图线、仪表刻度和低亮度驾驶舱质感。",
    defaultTheme: "airmap",
    previewBg: "#eef6fa",
    previewInk: "#172633",
    accent: "#2f82a2",
  },
  {
    id: "study",
    label: "东方书斋",
    description: "宣纸肌理、竹影、墨色边界和朱砂批注。",
    defaultTheme: "bamboo",
    previewBg: "#f5f1e5",
    previewInk: "#26251d",
    accent: "#9a3f2f",
  },
  {
    id: "darkroom",
    label: "暗房胶片",
    description: "银盐相纸、胶片颗粒和暗房红光。",
    defaultTheme: "contactsheet",
    previewBg: "#f2eee5",
    previewInk: "#25211c",
    accent: "#9a4f3c",
  },
  {
    id: "glitch",
    label: "故障霓屏",
    description: "扫描线、错位色块、信号噪声和高压霓虹。",
    defaultTheme: "coldglitch",
    previewBg: "#eef8ff",
    previewInk: "#101820",
    accent: "#00a6ff",
  },
  {
    id: "deconstruct",
    label: "解构杂志",
    description: "斜切版面、校样线、强对比排版和编辑部张力。",
    defaultTheme: "editorialwhite",
    previewBg: "#f7f4ea",
    previewInk: "#111111",
    accent: "#f03a2f",
  },
  {
    id: "system",
    label: "透明系统",
    description: "层叠窗口、HUD 细线、坐标网和冷静透明界面。",
    defaultTheme: "silveros",
    previewBg: "#edf3f7",
    previewInk: "#15212d",
    accent: "#5d7cff",
  },
] as const;

export const visibleThemeSeriesOptions = themeSeriesOptions.filter(
  (series) => !["archive", "atelier", "terminal"].includes(series.id),
);

export const themeOptions = [
  {
    value: "paper",
    series: "classic",
    label: "纸张日间",
    description: "暖白纸面",
    previewBg: "#fffdf7",
    previewInk: "#20211d",
    accent: "#c3452b",
  },
  {
    value: "daylight",
    series: "classic",
    label: "清亮日间",
    description: "冷白通透",
    previewBg: "#ffffff",
    previewInk: "#172126",
    accent: "#126c86",
  },
  {
    value: "mint",
    series: "classic",
    label: "薄荷日间",
    description: "柔和绿色",
    previewBg: "#fbfffc",
    previewInk: "#16221e",
    accent: "#2f7c5f",
  },
  {
    value: "focus",
    series: "classic",
    label: "专注日间",
    description: "低噪阅读",
    previewBg: "#fbfffd",
    previewInk: "#151b1c",
    accent: "#226f68",
  },
  {
    value: "night",
    series: "classic",
    label: "暖黑夜读",
    description: "暖色暗面",
    previewBg: "#23241f",
    previewInk: "#f1ede0",
    accent: "#e18a62",
  },
  {
    value: "midnight",
    series: "classic",
    label: "深蓝夜读",
    description: "蓝黑低光",
    previewBg: "#151b22",
    previewInk: "#e9f0f5",
    accent: "#76b7d8",
  },
  {
    value: "graphite",
    series: "classic",
    label: "石墨夜读",
    description: "中性深灰",
    previewBg: "#1d1e1a",
    previewInk: "#efefea",
    accent: "#d8b45a",
  },
  {
    value: "archive",
    series: "classic",
    label: "馆藏纸页",
    description: "纸纹、签条、墨色",
    previewBg: "#f5ecd8",
    previewInk: "#241f19",
    accent: "#8a3d2d",
  },
  {
    value: "catalog",
    series: "classic",
    label: "索引卡片",
    description: "卡片柜与蓝绿标签",
    previewBg: "#edf0e5",
    previewInk: "#1f2a24",
    accent: "#2f6f73",
  },
  {
    value: "umber",
    series: "classic",
    label: "褐墨夜档",
    description: "低光档案室",
    previewBg: "#211b16",
    previewInk: "#efe2c9",
    accent: "#c88345",
  },
  {
    value: "blueprint",
    series: "classic",
    label: "蓝图工作台",
    description: "网格、冷光、工程感",
    previewBg: "#eef4f7",
    previewInk: "#15232d",
    accent: "#286f9d",
  },
  {
    value: "studio",
    series: "classic",
    label: "白板工作台",
    description: "干净面板与红色标记",
    previewBg: "#f7f7f2",
    previewInk: "#20242a",
    accent: "#d04f35",
  },
  {
    value: "basalt",
    series: "classic",
    label: "玄武岩工作台",
    description: "深灰金属与蓝绿光",
    previewBg: "#15191d",
    previewInk: "#e6edf0",
    accent: "#49b8ad",
  },
  {
    value: "console",
    series: "classic",
    label: "荧光终端",
    description: "绿色低光",
    previewBg: "#101513",
    previewInk: "#d8f2df",
    accent: "#60d394",
  },
  {
    value: "amber",
    series: "classic",
    label: "琥珀终端",
    description: "暖黄字符与深棕底",
    previewBg: "#17120d",
    previewInk: "#ffe5b3",
    accent: "#ffb454",
  },
  {
    value: "aurora",
    series: "classic",
    label: "极光终端",
    description: "蓝绿光晕与深夜底",
    previewBg: "#0d1420",
    previewInk: "#e4f4ff",
    accent: "#6ee7d8",
  },
  {
    value: "riso",
    series: "poster",
    label: "双色孔版",
    description: "明黄、朱红与粗黑边",
    previewBg: "#fff056",
    previewInk: "#151515",
    accent: "#ff4d38",
  },
  {
    value: "cutout",
    series: "poster",
    label: "剪报拼贴",
    description: "白纸、青绿与番茄红",
    previewBg: "#faf7ee",
    previewInk: "#161616",
    accent: "#00a38a",
  },
  {
    value: "noir",
    series: "poster",
    label: "黑刊霓虹",
    description: "黑底、柠檬黄与热红",
    previewBg: "#111111",
    previewInk: "#f7f1d0",
    accent: "#f7dd36",
  },
  {
    value: "xerox",
    series: "poster",
    label: "复印蓝红",
    description: "高反差复印、青蓝和热粉",
    previewBg: "#f7f7f0",
    previewInk: "#111111",
    accent: "#00a6ff",
  },
  {
    value: "tabloid",
    series: "poster",
    label: "小报头版",
    description: "新闻纸、深蓝与醒目红",
    previewBg: "#f3ecd8",
    previewInk: "#171b26",
    accent: "#e33b2f",
  },
  {
    value: "sticker",
    series: "poster",
    label: "贴纸墙",
    description: "酸橙、莓粉与黑色描边",
    previewBg: "#dfff4f",
    previewInk: "#151515",
    accent: "#ff4fa3",
  },
  {
    value: "prism",
    series: "glass",
    label: "棱镜晨光",
    description: "透明柔光与珊瑚色焦点",
    previewBg: "#eef8f5",
    previewInk: "#142023",
    accent: "#ff7a70",
  },
  {
    value: "frost",
    series: "glass",
    label: "雾面玻璃",
    description: "冷雾面、墨绿和淡金光",
    previewBg: "#edf5f0",
    previewInk: "#182622",
    accent: "#4f9f83",
  },
  {
    value: "dusk",
    series: "glass",
    label: "暮色玻璃",
    description: "暗色玻璃、玫瑰和湖蓝",
    previewBg: "#111827",
    previewInk: "#eef6f2",
    accent: "#ff8c9a",
  },
  {
    value: "glacier",
    series: "glass",
    label: "冰川雾玻璃",
    description: "冰蓝霜面、冷白透光和细腻阴影",
    previewBg: "#eaf6ff",
    previewInk: "#102532",
    accent: "#58aee8",
  },
  {
    value: "pearl",
    series: "glass",
    label: "珍珠毛玻璃",
    description: "乳白珠光、淡桃色和柔和反射",
    previewBg: "#f9f1ea",
    previewInk: "#2a2020",
    accent: "#d98f86",
  },
  {
    value: "lagoon",
    series: "glass",
    label: "海雾毛玻璃",
    description: "水蓝、薄荷和湿润透明感",
    previewBg: "#e8fbf7",
    previewInk: "#12322e",
    accent: "#28b9a7",
  },
  {
    value: "smoke",
    series: "glass",
    label: "烟灰磨砂",
    description: "暗色磨砂、冷银边和柔光焦点",
    previewBg: "#15191f",
    previewInk: "#eef3f5",
    accent: "#a6c8ff",
  },
  {
    value: "airmap",
    series: "flight",
    label: "晴空航图",
    description: "淡蓝航图、细线刻度和清爽日间仪表。",
    previewBg: "#eef6fa",
    previewInk: "#172633",
    accent: "#2f82a2",
  },
  {
    value: "radar",
    series: "flight",
    label: "雷达晨雾",
    description: "雾绿雷达盘、柔和扫描线和低噪面板。",
    previewBg: "#edf4e9",
    previewInk: "#173027",
    accent: "#3f8c65",
  },
  {
    value: "beacon",
    series: "flight",
    label: "航标白昼",
    description: "米白舱表、橙色航标和深蓝刻线。",
    previewBg: "#f7f2e6",
    previewInk: "#24251f",
    accent: "#d17a28",
  },
  {
    value: "redcockpit",
    series: "flight",
    label: "红光夜航",
    description: "深夜座舱、红光仪表和静默蓝黑。",
    previewBg: "#10141c",
    previewInk: "#f4e7d3",
    accent: "#ff6b55",
  },
  {
    value: "bamboo",
    series: "study",
    label: "竹影书斋",
    description: "竹影、米纸和清润青绿。",
    previewBg: "#f5f1e5",
    previewInk: "#25271e",
    accent: "#557f52",
  },
  {
    value: "xuanpaper",
    series: "study",
    label: "雨窗宣纸",
    description: "宣纸白、雨痕灰和淡墨边界。",
    previewBg: "#f8f4ea",
    previewInk: "#28241d",
    accent: "#687b73",
  },
  {
    value: "cinnabar",
    series: "study",
    label: "朱砂批注",
    description: "暖纸面、朱砂印色和深墨正文。",
    previewBg: "#f6ead9",
    previewInk: "#2c241c",
    accent: "#b24737",
  },
  {
    value: "inklamp",
    series: "study",
    label: "墨灯夜读",
    description: "墨色夜幕、暖灯纸面和朱砂焦点。",
    previewBg: "#15130f",
    previewInk: "#f0e3c7",
    accent: "#c45b46",
  },
  {
    value: "contactsheet",
    series: "darkroom",
    label: "接触印相",
    description: "暖白相纸、胶片边框和棕红药水痕迹。",
    previewBg: "#f2eee5",
    previewInk: "#25211c",
    accent: "#9a4f3c",
  },
  {
    value: "silverprint",
    series: "darkroom",
    label: "银盐相纸",
    description: "冷灰相纸、银色颗粒和蓝黑文字。",
    previewBg: "#eef0ed",
    previewInk: "#20242a",
    accent: "#5f7188",
  },
  {
    value: "cyanotype",
    series: "darkroom",
    label: "蓝晒底片",
    description: "蓝晒纸、象牙正文和青蓝冲印感。",
    previewBg: "#e8f1f2",
    previewInk: "#102935",
    accent: "#2d7891",
  },
  {
    value: "safelight",
    series: "darkroom",
    label: "红灯暗房",
    description: "暗房红灯、深棕相纸和银盐高光。",
    previewBg: "#120d0b",
    previewInk: "#f3d8c4",
    accent: "#f0664d",
  },
  {
    value: "coldglitch",
    series: "glitch",
    label: "冷蓝故障",
    description: "冰蓝信号、错位边缘和清冷屏幕光。",
    previewBg: "#eef8ff",
    previewInk: "#101820",
    accent: "#00a6ff",
  },
  {
    value: "hotpink",
    series: "glitch",
    label: "热粉警报",
    description: "粉色告警、亮黑描边和高压电子标签。",
    previewBg: "#fff0f7",
    previewInk: "#1d1118",
    accent: "#ff2f88",
  },
  {
    value: "limeghost",
    series: "glitch",
    label: "绿屏残影",
    description: "荧光绿残影、浅底终端和漂移扫描线。",
    previewBg: "#edf9e8",
    previewInk: "#102116",
    accent: "#39d353",
  },
  {
    value: "blackout",
    series: "glitch",
    label: "黑场闪烁",
    description: "黑场噪点、洋红闪烁和电蓝边缘。",
    previewBg: "#07080d",
    previewInk: "#f2f7ff",
    accent: "#ff3df2",
  },
  {
    value: "editorialwhite",
    series: "deconstruct",
    label: "黑白主编",
    description: "黑白版心、斜切栏线和红色编辑标记。",
    previewBg: "#f7f4ea",
    previewInk: "#111111",
    accent: "#f03a2f",
  },
  {
    value: "proofred",
    series: "deconstruct",
    label: "红线校样",
    description: "校样纸、红线批改和粗黑版面边界。",
    previewBg: "#fff7f1",
    previewInk: "#17100d",
    accent: "#e60023",
  },
  {
    value: "fluoropage",
    series: "deconstruct",
    label: "荧光页码",
    description: "荧光页码、硬切色块和编辑台白底。",
    previewBg: "#fbffe1",
    previewInk: "#121212",
    accent: "#b6ff00",
  },
  {
    value: "midnightissue",
    series: "deconstruct",
    label: "午夜刊物",
    description: "黑底杂志、奶油文字和强光标题条。",
    previewBg: "#0b0b0c",
    previewInk: "#f5f1df",
    accent: "#f6d93b",
  },
  {
    value: "silveros",
    series: "system",
    label: "银白系统",
    description: "银白窗口、透明边框和蓝紫系统焦点。",
    previewBg: "#edf3f7",
    previewInk: "#15212d",
    accent: "#5d7cff",
  },
  {
    value: "icehud",
    series: "system",
    label: "极昼界面",
    description: "冰白 HUD、青色坐标线和轻透明层。",
    previewBg: "#f5fbff",
    previewInk: "#0f2835",
    accent: "#00bcd4",
  },
  {
    value: "ambertask",
    series: "system",
    label: "橙色任务",
    description: "暖灰系统、橙色任务灯和清晰操作面板。",
    previewBg: "#f7f4ec",
    previewInk: "#20232b",
    accent: "#ff8a00",
  },
  {
    value: "darkhud",
    series: "system",
    label: "暗蓝 HUD",
    description: "深蓝透明层、青色细线和低光系统面板。",
    previewBg: "#07121e",
    previewInk: "#e9f6ff",
    accent: "#36d7ff",
  },
] as const;

export function getThemesForSeries(seriesId: string) {
  const effectiveSeriesId = getEffectiveThemeSeries(seriesId);
  const themes = themeOptions.filter((theme) => theme.series === effectiveSeriesId);
  return themes.length ? themes : themeOptions.filter((theme) => theme.series === "classic");
}

export function getEffectiveThemeSeries(seriesId: string) {
  return visibleThemeSeriesOptions.some((series) => series.id === seriesId) ? seriesId : "classic";
}

export function getDefaultThemeForSeries(seriesId: string) {
  const effectiveSeriesId = getEffectiveThemeSeries(seriesId);
  return (
    visibleThemeSeriesOptions.find((series) => series.id === effectiveSeriesId)?.defaultTheme ??
    visibleThemeSeriesOptions[0].defaultTheme
  );
}

export const defaultShortcutBindings: ShortcutBindings = {
  search: "Ctrl+K",
  nextChapter: "N",
  previousChapter: "P",
  highlight: "H",
  export: "E",
  toggleLeft: "[",
  toggleRight: "]",
};

export const defaultSettings: AppSettings = {
  annotationContextChars: 100,
  themeSeries: "classic",
  theme: "paper",
  fontFamily: "Literata, Georgia, serif",
  fontSize: 18,
  lineHeight: 1.72,
  contentWidth: 820,
  pagePadding: 52,
  paragraphSpacing: 18,
  surface: "warm",
  borderStyle: "hairline",
  focusMode: false,
  shortcutBindings: JSON.stringify(defaultShortcutBindings),
};
